FROM node:24-alpine

RUN apk add --no-cache nginx curl && npm install -g npm

RUN mkdir -p /run/nginx /var/log/nginx && \
    chown -R nginx:nginx /var/log/nginx /run/nginx

COPY config/docker-config/frontend-nginx.conf /etc/nginx/nginx.conf

COPY config/docker-config/frontend-entrypoint.sh /usr/local/bin/frontend-entrypoint.sh
RUN chmod +x /usr/local/bin/frontend-entrypoint.sh

WORKDIR /app

COPY sentinel-kit_server_frontend/package*.json ./

ARG APP_ENV=prod
RUN if [ "$APP_ENV" = "prod" ]; then \
        npm install --silent; \
    fi

COPY sentinel-kit_server_frontend/ ./

ENTRYPOINT ["/usr/local/bin/frontend-entrypoint.sh"]