SQL_COMMANDS="
CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY '$MYSQL_EXPORTER_PASSWORD';
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
FLUSH PRIVILEGES;
"

echo "$SQL_COMMANDS" | mysql -u root -p"$MYSQL_ROOT_PASSWORD"